# frozen_string_literal: true

require_relative "stationery/version"
require_relative "stationery/errors"
require_relative "stationery/pdf/types"
require_relative "stationery/pdf/serializer"
require_relative "stationery/pdf/stream"
require_relative "stationery/pdf/writer"
require_relative "stationery/fonts/true_type"
require_relative "stationery/fonts/cmap"
require_relative "stationery/fonts/name_table"
require_relative "stationery/fonts/subset"
require_relative "stationery/fonts/registry"
require_relative "stationery/fonts/font"
require_relative "stationery/fonts/family"
require_relative "stationery/images/images"
require_relative "stationery/images/cache"
require_relative "stationery/images/scanlines"
require_relative "stationery/images/jpeg"
require_relative "stationery/images/png"
require_relative "stationery/color"
require_relative "stationery/geometry"
require_relative "stationery/page"
require_relative "stationery/resources"
require_relative "stationery/canvas/path"
require_relative "stationery/canvas/text"
require_relative "stationery/canvas"
require_relative "stationery/pdf/assembler"
require_relative "stationery/text/style"
require_relative "stationery/fonts/font_book"
require_relative "stationery/text/entities"
require_relative "stationery/text/markup"
require_relative "stationery/text/runs_builder"
require_relative "stationery/text/line"
require_relative "stationery/text/wrapper"
require_relative "stationery/text/paragraph"
require_relative "stationery/layout/node"
require_relative "stationery/layout/flow"
require_relative "stationery/layout/box"
require_relative "stationery/layout/row"
require_relative "stationery/layout/text"
require_relative "stationery/layout/image"
require_relative "stationery/layout/leaves"
require_relative "stationery/layout/table"
require_relative "stationery/layout/table/widths"
require_relative "stationery/layout/table/cell"
require_relative "stationery/layout/table/selection"
require_relative "stationery/layout/paginator"

# Pure-Ruby PDF documents built from Phlex-style components.
module Stationery
end
